# Configuration file

[audio]
s_rate = 16000
s_len = 64000
conv_mod = 'same'
#frame_size = 1024
#hop_size = 512

[json]
fname = 'info.json'
save_steps = 40

[logger]
level = 'debug'
#fname = 'history.log'

[neuralnet]
model_fname = 'model.h5'
optimizer = 'sgd'
loss = 'mse'
batch_size = 2
epochs = 1
[neuralnet.fnames]
input_data = 'data.npz'
input_labels = 'labels.npz'

[demo]
size = 'tiny'
datasets_url = 'https://raw.githubusercontent.com/polochinoc/various-audio-datasets/master/'
[demo.dnames]
input_dry = 'dry'
input_fx = 'fx'
output = 'wet'