# Configuration file

[audio]
s_rate = 16000
s_len = 64000
bit_depth = 16
mono = true
conv_mod = 'same'

[json]
fname = 'info.json'
save_steps = 40

[logger]
level = 'debug'

[neuralnet]
fname = 'model.h5'
batch_size = 2
epochs = 1
learning_rate = 2e-4

[data]
fname = 'data.npz'

[demo]
[demo.datasets]
#TODO: use complete URLs directly instead of using 'size'
size = 'tiny'
url = 'https://raw.githubusercontent.com/polochinoc/various-audio-datasets/master/'
[demo.dnames]
input_dry = 'dry'
input_fx = 'fx'
output = 'wet'