# Configuration file

[audio]
s_rate = 16000
s_len = 64000
bit_depth = 16
conv_mod = 'same'

[neuralnet]
fname = 'model.h5'
batch_size = 2
epochs = 40
save_steps = 5
learning_rate = 2e-3
decay = 4e-5

[data]
save_steps = 40
[data.json]
fname = 'info.json'
[data.numpy]
fname = 'data.npz'

[logger]
level = 'debug'

[demo]
[demo.urls]
dry = 'https://raw.githubusercontent.com/polochinoc/various-audio-datasets/master/note_dataset_medium.tar.gz'
fx = 'https://raw.githubusercontent.com/polochinoc/various-audio-datasets/master/ir_dataset_solo.zip'
[demo.dnames]
input_dry = 'dry'
input_fx = 'fx'
output = 'wet'