# Configuration file

repository_name = 'dereverberation-ml'

[audio]
s_rate = 16000
s_len = 64000
bit_depth = 16
conv_mod = 'same'
f_size = 2000

[neuralnet]
batch_size = 4
epochs = 150
save_steps = 2
learning_rate = 4e-3
decay = 5e-5
[neuralnet.dnames]
model = 'model'
predictions = 'predictions'

[data]
n_samples = 1200
[data.json]
fname = 'info.json'
save_steps = 50
[data.numpy]
fname = 'data.npz'

[logger]
level = 'debug'

[demo]
fx_name = 'fx.wav'
[demo.urls]
dry = 'http://download.magenta.tensorflow.org/datasets/nsynth/nsynth-test.jsonwav.tar.gz'
fx = 'https://impulses.prasadt.com/static/impulses/Lecture%20Hall.wav'
[demo.dnames]
input = 'dry'
output = 'wet'